### ISSUE TITLE
Plugin load failed 插件加载失败

### ISSUE THREAD

**Issue by declan-haojin** [HCLonely/hexo-online-server#1]
安装完成之后，`config.json`和`_config.yaml`都配置好了（除了hash密码，因为输入命令就会报错），运行`hexo online`报错，报错信息如下，请问有什么解决方案吗，谢谢！

```
express-session deprecated req.secret; provide secret option node_modules/hexo-online-server/server/app.js:21:9
ERROR Plugin load failed: hexo-online-server
Error: Cannot find module 'axios'
Require stack:
- /www/wwwroot/hexo/node_modules/hexo-online-server/server/routes/login.js
- /www/wwwroot/hexo/node_modules/hexo-online-server/server/app.js
- /www/wwwroot/hexo/node_modules/hexo-online-server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/www/wwwroot/hexo/node_modules/hexo-online-server/server/routes/login.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/www/wwwroot/hexo/node_modules/hexo-online-server/server/app.js:30:19)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/www/wwwroot/hexo/node_modules/hexo/lib/hexo/index.js:280:23)
    at /www/wwwroot/hexo/node_modules/hexo-online-server/index.js:4:11
    at /www/wwwroot/hexo/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/www/wwwroot/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:547:31)
```

**Comment by HCLonely** [comment]
有模块没装上，重新安装一下插件

**Comment by declan-haojin** [comment]
重新装了之后还是一样的报错。

安装的时候报错信息如下
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/hexo-blog-encrypt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/hexo-admin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ hexo-online-server@1.1.7
updated 1 package and audited 7293 packages in 16.994s

9 packages are looking for funding
  run `npm fund` for details

found 21 vulnerabilities (6 low, 6 moderate, 8 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by declan-haojin** [comment]
谢谢！希望能尽快修复，很需要一个在线编辑的插件。

**Comment by HCLonely** [comment]
已修复

**Comment by declan-haojin** [comment]
重新安装了一遍还是报错？

**Comment by HCLonely** [comment]
光推送到`github`, 忘发布到`npm`了, 现在应该可以了

**Comment by declan-haojin** [comment]
新的报错
```
ERROR Plugin load failed: hexo-online-server
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:454:10)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/www/wwwroot/hexo/node_modules/hexo-online-server/lib/getConfig.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/www/wwwroot/hexo/node_modules/hexo/lib/hexo/index.js:280:23)
    at /www/wwwroot/hexo/node_modules/hexo-online-server/index.js:2:19
    at /www/wwwroot/hexo/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/www/wwwroot/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/www/wwwroot/hexo/node_modules/bluebird/js/release/promise.js:729:18)
```

**Comment by HCLonely** [comment]
你的`onlineConfigPath`配置的什么

**Comment by declan-haojin** [comment]
哦不好意思，刚刚注释掉了，忘恢复了😂，谢谢！

**Comment by declan-haojin** [comment]
不好意思……还有一些问题：
运行`hexo online`之后显示已打开监听端口，但是访问不了，一直在加载页面
运行`hexo online`报错：
```
express-session deprecated req.secret; provide secret option node_modules/hexo-online-server/server/app.js:21:9
```

**Comment by declan-haojin** [comment]
另外我想请问一下我是把hexo博客直接部署在了云服务器，请问这个插件可以实现从`https://example/com/admin`进入在线编辑页面，然后进行在线生成部署博客吗？就是不需要git，只用`hexo g`

**Comment by HCLonely** [comment]
是的

**Comment by declan-haojin** [comment]
好像是因为我没有设置`secret`,请问这个该怎么设置，小白真心不会，感谢！

**Comment by HCLonely** [comment]
这是用来加密cookie的字符串，越复杂越好

**Comment by declan-haojin** [comment]
请问方便加一下您的qq或其他联系方式吗，我的问题还挺大的，如果您有时间，希望能够得到您的指导。我的qq是1913279201

**Comment by declan-haojin** [comment]
```
GET /shell?action=clean 500 4.090 ms - 2419
GET /shell?action=server 500 2.664 ms - 2518
GET /shell?action=deploy 500 2.227 ms - 2419

```

**Comment by HCLonely** [comment]
加我QQ吧1606051253
